v0_init: -10.0
T_max: 0.4
h_init: 0.0001
alpha_hht: -0.1
contact_model: lankarani-nikravesh
k_wall: 45000000.0
cr_wall: 0.8
n_masses: 7
masses:
- 14333.333333333334
- 28666.666666666668
- 14333.333333333334
- 14333.333333333334
- 14333.333333333334
- 28666.666666666668
- 14333.333333333334
x_init:
- 0.0
- 3.0
- 6.5
- 10.0
- 13.5
- 17.0
- 20.0
y_init:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
fy:
- 28666666.666666668
- 28666666.666666668
- 28666666.666666668
- 28666666.666666668
- 28666666.666666668
- 28666666.666666668
uy:
- 0.08
- 0.08
- 0.08
- 0.08
- 0.08
- 0.08
bw_a: 0.0
bw_A: 1.0
bw_beta: 0.1
bw_gamma: 0.9
bw_n: 8
friction_model: lugre
mu_s: 0.35
mu_k: 0.25
sigma_0: 1.0e5
sigma_1: 3.16e2
sigma_2: 0.4
newton_tol: 0.0001
max_iter: 50
angle_rad: 0.0
d0: 0.01
collision:
  scenario: EN15227_2011_C2_baseline
case_name: generic_passenger__EN15227_C2
notes: '[auto] EN15227 C2: target_mass=129000 kg, scale=2.388889, v0_init=-10.0000
  m/s, scenario=EN15227_2011_C2_baseline.'
