# Only keys you put here override the defaults from _default_config_dict()

v0_init: -22.22        # â‰ˆ 80 km/h towards the wall
T_max: 0.40            # longer simulation time
alpha_hht: -0.15
contact_model: "lankarani-nikravesh"

# You can override stiffness as well:
k_wall: 45_000_000.0   # 45 MN/m
cr_wall: 0.8
