case_name: ICE1_powercar_discrete6
notes: ICE 1 power car discretized into 6 equal masses (78 t total). Simplified uniform
  stiffness/yield for all inter-mass springs.
v0_init: -22.22
T_max: 0.3
h_init: 0.0001
alpha_hht: -0.15
contact_model: lankarani-nikravesh
k_wall: 45_000_000.0   # 45 MN/m
cr_wall: 0.8
n_masses: 6
masses:
- 13000.0
- 13000.0
- 13000.0
- 13000.0
- 13000.0
- 13000.0
x_init:
- 0.0
- 3.6
- 7.2
- 10.8
- 14.4
- 18.0
y_init:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
k_train:
- 140625000.0
- 140625000.0
- 140625000.0
- 140625000.0
- 140625000.0
fy:
- 9000000.0
- 9000000.0
- 9000000.0
- 9000000.0
- 9000000.0
uy:
- 0.064
- 0.064
- 0.064
- 0.064
- 0.064

d0: 0.01
